version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=vsignals
      - POSTGRES_PASSWORD=VSignals123
      - POSTGRES_DB=vsignals
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres-db-volume:
    driver: local
